version: 2.1
jobs:
  node-version-job:
    docker: 
      - image: cimg/node:23.5.0
    steps:
     - run:
         name: "Node Version Display"
         command: node --version
     - run:
         name: "Print Current Working Directory of Circle CI Project"
         command: echo $CIRCLE_WORKING_DIRECTORY
     - run: 
         name: "Printing present working directory"
         command: pwd
       
         
       
       # - echo "Current working directory is: $CIRCLE_WORKING_DIRECTORY
workflows:
  wf-001:
    jobs:
      - node-version-job
