version: 2.1
jobs:
  node-version-job:
    docker: 
      - image: cimg/node:23.5.0
    steps:
     - run: node --version
     - run: echo "Current working directory is: $CIRCLE_WORKING_DIRECTORY"
workflows:
  wf-001:
    jobs:
      - node-version-job
